### ISSUE TITLE
Bug in Discrete Lunar Lander

### ISSUE THREAD

**Issue by obokaiwele** [shivaverma/OpenAIGym#2]
The code in https://github.com/shivaverma/OpenAIGym/blob/master/lunar-lander/discrete/lunar_lander.py#L108 says

```python
if is_solved > -200:
    print('\n Task Completed! \n')
```

It should be 
```python
if is_solved > 200:
    print('\n Task Completed! \n')
```

Because the environment is considered solved when the average score of the last 100 episodes is > 200, not when > -200

**Comment by shivaverma** [comment]
@obokaiwele  Fixed this. It was a typo. Thanks for pointing out.
